Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [13]:
import numpy as np
rows,cols = 3,3
numbers = np.arange(2, 11)  
matrix = numbers.reshape(rows, cols)
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

In [14]:
import numpy as np
vector = np.zeros((10))
vector[5] = 11
vector

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [15]:
import numpy as np
rows,cols = 5,5
array_2d = np.zeros((rows, cols),dtype = int)
array_2d[1:4, 1:4] = 1
array_2d

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

Write a NumPy program to add a border (filled with 0's) around an existing array.

In [16]:
import numpy as np
existing_array = np.array([[1, 2],[3, 4],[5, 6]])
border_size = 1
r, c = existing_array.shape
new_r = rows + 2*border_size
new_c = cols + 2*border_size
new_array = np.zeros((new_r, new_c), dtype=existing_array.dtype)
new_array[border_size:border_size + rows, border_size:border_size + cols] = existing_array
new_array

ValueError: could not broadcast input array from shape (3,2) into shape (5,5)

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

In [ ]:
import numpy as np
if cx_nos_str.strip(): 
	complex_numbers = np.array([complex(num.strip()) for num in cx_nos_str.split(',')])
	real_parts = np.real(complex_numbers)
	imaginary_parts = np.imag(complex_numbers)

	print("Complex Numbers:", complex_numbers)
	print("Real Parts:", real_parts)
	print("Imaginary Parts:", imaginary_parts)
else:
	print("No complex numbers provided.")

No complex numbers provided.


### Step-by-Step Beginner Level Program to Find Real and Imaginary Parts of Complex Numbers
This program demonstrates how to find the real and imaginary parts of an array of complex numbers using user-defined input.

In [ ]:
import numpy as np
x = np.array([1.0 + 0.j, 0.70710678 + 0.70710678j])
print("Original array", x)
print("Real part of the array:")
print(x.real)
print("Imaginary part of the array:")
x.imag

Original array [1.        +0.j         0.70710678+0.70710678j]
Real part of the array:
[1.         0.70710678]
Imaginary part of the array:


array([0.        , 0.70710678])

Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [ ]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])

print("Array1:", array1)
print("Array2:", array2)

result = np.isin(array1, array2)
print("Compare each element of array1 and array2")
result

Array1: [ 0 10 20 40 60]
Array2: [ 0 40]
Compare each element of array1 and array2


array([ True, False, False,  True, False])

Write a NumPy program to get the unique elements of an array.

In [ ]:
import numpy as np
array1 = np.array([10, 10, 20, 20, 30, 30])

print("Original array:")
print(array1)
unique_elements = np.unique(array1)
print("Unique elements of the above array:")
print(unique_elements)
array1 = np.array([[1, 1], [2, 3]])
print("Original array:")
print(array1)
unique_elements = np.unique(array1)
print("Unique elements of the above array:")
print(unique_elements)
array2 = np.array([0, 40])
print("Array2:", array2)

comparison_result = np.in1d(array1, array2)
print("Compare each element of array1 and array2")
comparison_result


Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]
Array2: [ 0 40]
Compare each element of array1 and array2


C:\Users\Hirak\AppData\Local\Temp\ipykernel_3644\158180128.py:18: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  comparison_result = np.in1d(array1, array2)


array([False, False, False, False])

Write a NumPy program to find the set difference between two arrays. The set difference will return sorted, distinct values in array1 that are not in array2.

In [ ]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])
setdiff = np.setdiff1d(array1, array2)
print("Set difference of array1 and array2:")
print(setdiff)

Set difference of array1 and array2:
[ 0 20 60 80]


Write a NumPy program to find the union of two arrays. Union will return a unique, sorted array of values in each of the two input arrays.

In [ ]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
print(np.unique(np.concatenate((array1, array2))))

[ 0 10 20 30 40 50 60 70 80]


Write a NumPy program to construct an array by repeating.

In [ ]:
import numpy as np
org_array = np.array([1,2,3,4])
print("Original array: ")
print(org_array)
repeat_array_2 = np.tile(org_array, 2)
print("Repeat each element of the above array: ")
print(repeat_array_2)
repeat_array_3 = np.tile(org_array, 3)
print("Repeat each element of the above array: ")
print(repeat_array_3)

Original array: 
[1 2 3 4]
Repeat each element of the above array: 
[1 2 3 4 1 2 3 4]
Repeat each element of the above array: 
[1 2 3 4 1 2 3 4 1 2 3 4]


Write a NumPy program to repeat array elements

In [21]:
import numpy as np
org_array = np.array([1,2,3,4])
print("Original array: ")
print(org_array)
a=int(input("Enter the number of times to repeat: "))
repeat_array_2 = np.repeat(org_array, a)
print("Repeat each element of the above array: ")
print(repeat_array_2)

Original array: 
[1 2 3 4]
Repeat each element of the above array: 
[1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4]


Write a NumPy program to compare two arrays using NumPy

In [22]:
import numpy as np
a = np.array([1,2])
b = np.array([4,5])
print("a > b:", a > b)
print("a >= b:", a >= b)
print("a < b:", a < b)
print("a <= b:", a <= b)

a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


Write a Numpy program to sort the row wise Matrix

In [4]:
import numpy as np
matrix = np.array([[3, 7, 1], [6, 5, 4], [9, 2, 8]]) 
sorted_matrix = np.sort(matrix, axis=1)
print("Original matrix: ")
print(matrix)
print("Sorted matrix: ")
print(sorted_matrix)

Original matrix: 
[[3 7 1]
 [6 5 4]
 [9 2 8]]
Sorted matrix: 
[[1 3 7]
 [4 5 6]
 [2 8 9]]


Write a numpy program to turn a matrix left and right.

In [7]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rotated_left = np.rot90(matrix, k=1)
rotated_right = np.rot90(matrix, k=-1)
print("Original matrix:")
print(matrix)
print("Rotated matrix left:")
print(rotated_left)
print("Rotated matrix right:")
print(rotated_right)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rotated matrix left:
[[3 6 9]
 [2 5 8]
 [1 4 7]]
Rotated matrix right:
[[7 4 1]
 [8 5 2]
 [9 6 3]]


Matrix multiplication using numpy.

In [8]:
import numpy as np
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
multiplied_matrix = np.multiply(matrix1, matrix2)
print("Multiplied matrix:")
print(multiplied_matrix)

Multiplied matrix:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


Write a Numpy Program to convert a matrix into 1D array

In [6]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
one_dimensional_array = matrix.flatten()
one_dimensional_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Write a NumPy program to create another shape from an array without changing its data.

In [7]:
import numpy as np
rows=int(input("Enter the number of rows: "))
cols=int(input("Enter the number of columns: "))
matrix = np.zeros((rows, cols))
print("Matrix with zeros:")
print(matrix)
reshape_rows=int(input("Enter the number of rows for reshaping: "))
reshape_cols=int(input("Enter the number of columns for reshaping: "))
if(reshape_rows * reshape_cols != rows * cols):
    print("Reshape is not possible.")
else:
    reshaped_matrix = matrix.reshape(reshape_rows, reshape_cols)
    print("Reshaped matrix:")
    print(reshaped_matrix)

Matrix with zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Reshaped matrix:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Write a numpy program to print the element ask from user.

In [27]:
import numpy as np
matrix = np.array([[14, 27, 31, 44, 53], 
                   [68, 75, 81, 92, 10], 
                   [11, 412, 92, 184, 115], 
                   [162, 174, 189, 179, 230]])
print("Matrix:")
print(matrix)
#row_index = int(input("Enter the row index (0-indexed): "))
#col_index = int(input("Enter the column index (0-indexed): "))
numberofrows = matrix.shape[0]
numberofcols = matrix.shape[1]
element = int(input("Enter the index to find its element: "))
count=0
for i in range(numberofrows):
    for j in range(numberofcols):
        count=count+1
        if(count==element):
            print("The element at the index is: ",matrix[i][j])

Matrix:
[[ 14  27  31  44  53]
 [ 68  75  81  92  10]
 [ 11 412  92 184 115]
 [162 174 189 179 230]]
The element at the index is:  92


Write a Numpy Program to concatenate two dimensional Arrays

In [4]:
import numpy as np
array1_2d = np.array([[0, 1, 3], [5, 7, 9]])
array2_2d = np.array([[0, 2, 4], [6, 8, 10]])
np.concatenate((array1_2d, array2_2d), axis=1)




array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

Splits an array of shape 4*4 into two arrays along the second axis.

In [ ]:
import numpy as np
array_4X4 = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])

print("Original array:")
print(array_4X4)
print("Split into two arrays along the second axis:")
print(np.split(array_4X4, 2, axis=1))


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Split into two arrays along the second axis:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


To combine a one and two dimensional array together and display there elements.

In [34]:
import numpy as np
one_dimensional_array = np.array([0, 1, 2, 3])
print("one_dimensional_array: ")
print(one_dimensional_array)
two_d_array = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print("2D array: ")
print(two_d_array)
one_dimensional_array_reshaped = one_dimensional_array.reshape(1, -1) 
concatenated_array = np.concatenate((one_dimensional_array_reshaped, two_d_array), axis=0)
print("Concatenated array: ")
print(concatenated_array)


one_dimensional_array: 
[0 1 2 3]
2D array: 
[[0 1 2 3]
 [4 5 6 7]]
Concatenated array: 
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]
